package com.rabbit.mechanic.enumerators;

/**
 * An enumerator for car brands
 */
public enum CarBrands {
    ABARTH("Abarth"),
    ABT("ABT"),
    ACURA("Acura"),
    AIXAM("Aixam"),
    ALFA_ROMEO("Alfa Romeo"),
    ALPINA("Alpina"),
    ALPINE("Alpine"),
    APOLLO("Apollo"),
    ARASH("Arash"),
    ARCFOX("Arcfox"),
    ARIEL("Ariel"),
    ARRINERA("Arrinera"),
    ARRIVAL("Arrival"),
    ARTEGA("Artega"),
    ASTON_MARTIN("Aston Martin"),
    AUDI("Audi"),
    BENTLEY("Bentley"),
    BESTUNE("Bestune"),
    BHARATBENZ("BharatBenz"),
    BMW("BMW"),
    BRABUS("Brabus"),
    BRILLIANCE("Brilliance"),
    BUGATTI("Bigatti"),
    BUICK("Buick"),
    CADILLAC("Cadillac"),
    CANOO("Canoo"),
    CAPARO("Caparo"),
    CARLSSON("Carlsson"),
    CATERHAM("Caterham"),
    CHANGAN("Changan"),
    CHERY("Chery"),
    CHEVROLET("Chevrolet"),
    CHRYSLER("Chrysler"),
    CITROEN("Citroen"),
    DACIA("Dacia"),
    DAF("DAF"),
    DAIHATSU("Daihatsu"),
    DAIMLER("Daimler"),
    DATSUN("Datsun"),
    DAVID_BROWN("David Brown"),
    DINA("DINA"),
    DODGE("Dodge"),
    DONGFENG("Dongfeng"),
    DS("DS"),
    ELEMENTAL("Elemental"),
    EXEED("Exeed"),
    FARADAY_FUTURE("Faraday Future"),
    FERRARI("Ferrari"),
    FIAT("Fiat"),
    FORD("Ford"),
    FOTON("Foton"),
    GEELY("Geely"),
    GENESIS("Genesis"),
    GINETTA("Ginetta"),
    GMC("GMC"),
    HAVAL("Haval"),
    HOLDEN("Holden"),
    HONDA("Honda"),
    HONGQI("Hongqi"),
    HUMMER("Hummer"),
    HYUNDAI("Hyundai"),
    INFINITI("Inifiniti"),
    ISUZU("Isuzu"),
    IVECO("Iveco"),
    JAGUAR("Jaguar"),
    JEEP("Jeep"),
    JETTA("Jetta"),
    KAMAZ("Kamaz"),
    KARMA("Karma"),
    KEATING("Keating"),
    KENWORTH("Kenworth"),
    KIA("Kia"),
    KOENIGSEGG("Koenigsegg"),
    LAGONDA("Lagonda"),
    LAMBORGHINI("Lamborghini"),
    LANCIA("Lancia"),
    LAND_ROVER("Land Rover"),
    LARAKI("Laraki"),
    LEVC("Levc"),
    LEXUS("Lexus"),
    LIGIER("Ligier"),
    LINCOLN("Lincoln"),
    Lister("Lister"),
    LORDSTOWN("Lordstown"),
    LOTUS("Lotus"),
    LUCID("Lucid"),
    LUXGEN("Luxgen"),
    MACK("Mack"),
    MAN("MAN"),
    MASERATI("Maserati"),
    MAYBACH("Maybach"),
    MAZ("MAZ"),
    MAZDA("Mazda"),
    MAZZANTI("Mazzanti"),
    MCLAREN("McLaren"),
    MELKUS("Melkus"),
    MERCEDES("Mercedes-Benz"),
    MG("MG"),
    MINI("MINI"),
    MITSUBISHI("Mitsubishi"),
    MOSLER("Mosler"),
    NEVS("NEVS"),
    NIKOLA("Nikola"),
    NIO("NIO"),
    NISSAN("Nissan"),
    NOBLE("Noble"),
    OPEL("Opel"),
    PACCAR("Paccar"),
    PAGANI("Pagani"),
    PANOZ("Panoz"),
    PERODUA("Perodua"),
    PEUGEOT("Peugeot"),
    POLESTAR("Polestar"),
    PONTIAC("Pontiac"),
    PORSCHE("Porsche"),
    PROTON("Proton"),
    RAM("RAM"),
    RENAULT("Renault"),
    REZVANI("Rezvani"),
    RIMAC("Rimac"),
    RIVIAN("Rivian"),
    ROLLS_ROYCE("Rolls Royce"),
    ROSSION("Rossion"),
    ROVER("Rover"),
    RUF("RUF"),
    SAAB("SAAB"),
    SALEEN("Saleen"),
    SATURN("Saturn"),
    SCANIA("Scania"),
    SEAT("Seat"),
    SINGULATO("Singulato"),
    SISU("Sisu"),
    SKODA("Skoda"),
    SMART("SMART"),
    SPYKER("Spyker"),
    SSC("SSC"),
    SUBARU("Subaru"),
    SUZUKI("Suzuki"),
    TECHART("TechArt"),
    TESLA("Tesla"),
    TOYOTA("Toyota"),
    TRION("Trion"),
    TROLLER("Troller"),
    TVR("TVR"),
    VAUXHALL("Vauxhall"),
    VECTOR("Vector"),
    VENCER("Vencer"),
    VINFAST("VinFast"),
    VLF("VLF"),
    VOLKSWAGEN("Volkswagen"),
    VOLVO("Volvo"),
    WELTMEISTER("Weltmeister"),
    WEY("Wey"),
    WORKHORSE("Worlkhourse"),
    WULING("Wuling"),
    XPENG("Xpeng"),
    ZENVO("Zenvo");

    private String name;

    CarBrands(String name) {
        this.name = name;
    }

    /**
     * Get name of brand
     * @return brand name
     */
    public String getName() {
        return name;
    }
}
